name: hexpm-release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Generate documentation
        run: rebar3 edoc

      - name: Publish to hex.pm
        run: DEBUG=1 rebar3 hex publish --repo hexpm --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
